### ISSUE TITLE
ffmpeg process exited with code 1

### ISSUE THREAD

**Issue by Smallkan** [DasKraken/CR-dl#6] opened 2019-02-13 07:18 UTC
Download error:

Downloading S(01/01)E(01/12) - HINAMATSURI Episode 1
(HTML5 Player)
Following subtitles will be included:
Downloading to "HINAMATSURI [720p]/HINAMATSURI - 01 - Arrival of the Psychokinetic Girl! [720p].mkv"...
downloading [████████████████████████████████████████] 100% | 364 MB/364 MB | Speed: 176 MB/s | ETA: 0s
muxing [░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0% | {curDuration}/{totalDuration} | Speed: {fps} fps
RuntimeException: ffmpeg process exited with code 1
    at ChildProcess.proc.on (/usr/local/lib/node_modules/cr-dl/src/processVideo.js:82:24)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

**Comment by DasKraken** [comment] 2019-02-15 14:54
Duplicate of #5

**Closed** 2019-02-15 15:09 UTC
